[package]
name = "memelite_custom_memes"
version = "0.1.0"
edition = "2024"
description = "Rust port of legacy meme-generator <0.1.14 memes for meme-generator 0.2.3"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
inventory = "0.3"
serde = "1.0"
skia-safe = { version = "0.93", features = ["textlayout"] }
meme_generator_core = "0.0.5"
meme_generator_utils = "0.0.9"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
